language: go
go:
  - 1.x

addons:
  hosts:
    - dom1.acmetool-test.devever.net
    - dom2.acmetool-test.devever.net
    - boulder
    - boulder-mysql
    - boulder-rabbitmq
    - publisher.boulder
    - ra.boulder
    - ca.boulder
    - va.boulder
    - sa.boulder
  apt:
    packages:
      - lsb-release
      - gcc
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - rsyslog
      - libcap-dev
      - gcc-multilib
      - libc6-dev-i386
      - libcap-dev:i386
      - debhelper
      - devscripts
      - realpath
      - dput
      - gnupg
      - lintian
      - ncftp
      - rpm
  mariadb: "10.1"

sudo: false

services:
  - rabbitmq

before_install:
  - source ./.travis/before_install
install:
  - go get -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success
before_cache:
  - source ./.travis/before_cache

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "OA/Trkip03Ee3145oxrbHv3oM7dFpoX2h3y65CzyecQ2v8X4/l5pOwyMiJei5i20zm+QrK0iP9JttbDR9hY71d1DoxMXRGW0YHGFEutUQLZFpkPHLv7klSq8RjRGzpusSaxAtpEF27ZS+7NU42awYynWDzVsK4cglH9CimrS1glr2lKA5bXucqFROlqbI5GzXEdZJXhdGlKZWQWo83Hwe8JTwvIN8xRn5xZ33yxeMDl6SgQ3UhEs6zmsAQphGZ1pNcQaPjtyFtwEBeVQCsYW0loo8gUyjsfippSfGciu+g1J6sGVBj3HxGWWKmMa7lMaCEpL5CUKVcT2WH+LefYLHX5ZkyK8EQwt8QzrO1+X268+SulbWu2rf9SFQlLgoazIa8N8qfd8wVlo6Z3Jiy5YNHhHImMRYtgh5q3lo/5COUrPSgPBx4+VdciuMLxVYw96lTrPcMd4/J2gVYAf7f3AXeOpi/zF0T1WyD/64X0xKquYrbBzGbrEH4EM68vXQBiK5Q2sAEwhMUZNhgAqlKRzpqQoe/Cdx/Stm6cuFt6r87TbJfYiHGCZehveASWwH/Nk1HogOXjv/iVikxOqUiuqy0Q7GLPuFdcAGuLjqxS3wmdN1pBEGVqtSKA/3xrJptKlniz6+1hWr+H1ttTRTgok6ViX/POf+CW11VsfVo7qjyc="
    # PPA_ENCRYPTION_ID
    - secure: "oYuMlIP0jJZpvw1V6HKcieHW/HcYX2X+5znZ7lLcroyz3uW8ZtdRo0mDBFmSJuxpxWA/6uNdB/ReV5hhSBGM+XsIB04FAhgp6dOOT9Z7ncE92d4SBkofYh0Le7gX/2DbtsDXBWJt8RLrCbnh/b7Nu51XXELu4vFPrp9RB28iYiCZqJxnEFf/4XMoWsfV/qUL7xaa54KC3Fhmyx5TpTtneJemhkPHc91z2SFv/v//QON6h/HZla5jgu0Ncxm6sCzGvLI6Rp4UGT1x0jifzqJ4WwCOvLCdHwy2KOq0hJFrRybfgWgo8o36CT7uTmisanWNvI/kQMZr/WqvRP7+OXBrA9dnGX6TUpHW+nigq+AopIjAWkshKUZDL53oMl3zWUdryD36fjxSYnxHo4I/6ocoZFRCh/hSClLwNvDyjsugqQhBY6gUSlFItHyubdFV8L5r1ehhwafE6Mz9OqqVZhW3LAlUOhvKruv8WA7gGKYc2IwRNRCql/Glun7OZk2JB2SuwJnNCn63HqAAs1QMWHaHrFCeGLj8GqZM0P2dNXYfS2M/g1691l/IYtQLwNFCLmzBEdkNF2uytoqq+VGwZSx6waxCybWwI9selPjvFrWB9dk3WVjiDmg2g1qZshr0jPLaCBC5imw0oSobjV0lJefANeTsmrX6PAZlTbLZhjvclIg="
    # PPA_ENCRYPTION_PASS
    - secure: "Edr/h71sDFi2aXxICO3Ij5twLl/83HEwTgWfQ6/dJ7BcavjONTDyzB8cNQ0dGjlljujtbyyoD0+89Wu5pVotkv49JUZpQoWOJdn/9kyxFi9u61cpABSZvU/Sr1pWkOkDra7oAxgcJTAwNg5j1OVJ3+wfxJGGRVTotqPXc+hpIKx6z7jKR22D0Adz4uu1hWzRMdw8Qp8opqBJG2YHwvIF51U/Ztz4FcNwq1LJ1kdZ5YJYvU4SG6zm9+Q2XdjNQivLPuMdNL+s5Ik6J8Iiftu/OvxsSdfPClxyg0r8VCnoM8vpPAJc0BAOo6FBwUFLHfhFkUHUuLtZR/gyh5zkTd7fhRvdM/Sc94Dd9r2PeN8Jh5sTpn5a8/Qyhq/JItjcuRBB0Ysl4cZR81eIvPMeW4R3cnZ5mTA3rOpYjswiWAxBvJ6ZCOmGbtDG3lTkMUZ8Po6DmTqXMRRfWa/Nsuju5360UC65Q7mmHZx+hOTgeDw1LlMEhcG+ac2QH/FbnVM/SnRsYw+y5QORWJlFMcqPCwsGEVD2FxkuxX/tOtbIdyyBvQNEbdx+3/NpmwmUnQgH0v4i0o6rlQ65ETw6CdMNt9P+RuhRvrisbDvm/lwwfPT2IJenElB6Xu3Xz/i2WbAty92XJYfxpiIz1Rpivfu89OsyqKsMKzmhOqSfq6W2QxPuW8k="
    # COPR_LOGIN_TOKEN expires=2018-02-15
    - secure: "X9xS2wGSeYXcPp8vs7z8nrzhtcvp8yLd+8vx+NaQuymX0S22tqLKzCSbkIaDk68GFpMxk19a9Tx4drLTq786uDvvpSe4PqzOdXJhiX1ZiwsGoltqET0z2JTm5c/b57Aj9SzLaKKUTjzlu9tAG9l0a82lsx5enm4uh2oOooLvk1nneXiiL01ijSr6FaN1q5jRhREcpglSDx8dXcgXHqq1xC8xVoQlxGqdNaWKBuV/HndLp7mKCwXTx1fDZRdS0m2+nWirUL1VN6jCduAVi9OYiNMYYlxu5qdBP5Nvt7sPgrZRIvHe+pNjLRmsWz6/sB3wnV/fgNo2va+0MfjcCCJUfqWyTti2tXgcYf77wXH+eHZrwSPeic5E5VAx3fFY1SKYoxk8CxCdE6WCCIlPNUtTxcY+TdNXV0nSxkRPJsxh25o9iT6I5K5Z8V/15cCGu6MkPSDV9UYalgdGu9IbMOevXqjmLudR5yV36p4VGWN6Kq5MwCc1jv9CjqfaRpWNVk0uqqPZ6+pNWqMegnhxkFSPlJCtxM6I0+Rm5KAf93pIrLAEF6vF5i7pxuGqedo+533GiWSy9oBGqh8uHknY3djT1V/8RKh3ln30BrHDd3BM+AEwJdAS8NA8E7X8yaqHTT92p5clgXGlqFIZay4baVa1tJ4UJK7Kz2lVCisT5NMWOqY="

branches:
  only:
    - master
    - dev
    - /^test-.*$/
    - /^v[0-9].*$/
cache:
  directories:
    - $HOME/tcache

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MDE0ODgzMyUzQW1hdHJpeC5vcmcvJTIxSWhNWURnRHl4aXVjUlpMSW1yJTNBbWF0cml4Lm9yZw"
    on_success: change
    on_failure: always
    on_start: never
